### ISSUE TITLE
Overriding of Normative reference boilerplate doesn't work

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/metanorma-ribose#93]
```
[bibliography]
== Normative references

The following contract document is referred to in the text in such a
way that some or all of its content constitutes requirements of this
document.
```

Still shows this:

<img width="479" alt="Screenshot 2021-03-30 at 1 29 19 PM" src="https://user-images.githubusercontent.com/11865/112938296-f0076500-915b-11eb-820e-0cee5cd1ba08.png">

**Comment by opoudjis** [comment]
The `[.boilerplate]` override of the default text in terms sections has not been extended to normative references.

**Comment by opoudjis** [comment]
Cannot use the same strategy as for terms & definitions boilerplate: cannot insert a hanging clause before references, since the references will end up within that hanging clause, and the bibliography status of the parent clause will not inherit into the bibliography list.

Instead, will need to make this a boilerplate Note, which is stripped of its note wrapper in postprocessing.

**Comment by opoudjis** [comment]
Realised as:

````
[bibliography]
== Normative references

[NOTE,type=boilerplate]
--
The following contract document is referred to in the text in such a
way that some or all of its content constitutes requirements of this
document.
--
````
